language: python
python:
- '2.7'

os:
  - linux
#  - osx

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - gfortran
    - libgsl0-dev
    - cmake
    - libfftw3-3
    - libfftw3-dev
    - libmpfr4
    - libmpfr-dev
    - libhdf5-serial-dev
    - hdf5-tools
    - libopenmpi-dev
    - openmpi-bin

compiler:
  - gcc

install:
- pip install numpy scipy matplotlib nose docutils mpi4py h5py
- ./configure
- make framework

virtualenv:
  system_site_packages: false

script:
- export PYTHONPATH=${PWD}/src
- nosetests -e "test_grid_implementation" -e "test_plot" test/core_tests
